// Package collector wraps the upstream OpenTelemetry Collector that ships
// embedded in the Conduit binary. The factory map (see components.go) is
// generated by OCB from builder-config.yaml at the repo root and folded into
// this directory by 'make build-ocb'. Everything else in this package is
// hand-written and is the contract that cmd/run depends on.
//
// Lifecycle:
//
//	settings := collector.DefaultSettings(buildInfo)
//	settings.ConfigProviderSettings.ResolverSettings.URIs = []string{"yaml:" + renderedYAML}
//	if err := collector.Run(ctx, settings); err != nil { ... }
//
// DefaultSettings registers every component listed in builder-config.yaml
// (see ADR-0004, "pure upstream components only"). Run drives a single
// otelcol.Collector from settings; the caller is responsible for setting
// the configuration URIs (typically a "yaml:" URI built from internal/expander
// output) before calling.
//
// Windows-service integration (svc.Run + SCM dispatch) lands at M4 alongside
// the .msi packaging story; until then the collector runs in the foreground
// on every platform.
package collector

import (
	"context"
	"fmt"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap"
	envprovider "go.opentelemetry.io/collector/confmap/provider/envprovider"
	fileprovider "go.opentelemetry.io/collector/confmap/provider/fileprovider"
	httpprovider "go.opentelemetry.io/collector/confmap/provider/httpprovider"
	httpsprovider "go.opentelemetry.io/collector/confmap/provider/httpsprovider"
	yamlprovider "go.opentelemetry.io/collector/confmap/provider/yamlprovider"
	"go.opentelemetry.io/collector/otelcol"
)

// DefaultBuildInfo is the BuildInfo used when callers do not supply their own.
// cmd/version (M3) overrides this via ldflags so 'conduit version' surfaces
// the real release/git SHA; until then DefaultSettings keeps a stable
// dev-default that exercises the right code path.
var DefaultBuildInfo = component.BuildInfo{
	Command:     "conduit",
	Description: "Conduit — OpenTelemetry Collector distribution (V0)",
	Version:     "0.0.0-dev",
}

// DefaultSettings returns an otelcol.CollectorSettings populated with all V0
// components registered (see components.go) and the standard set of confmap
// URI providers (env / file / http / https / yaml) so configuration can be
// loaded from local files, in-memory YAML, or remote endpoints.
//
// If buildInfo has a zero Command, DefaultSettings substitutes
// DefaultBuildInfo. cmd/run relies on this so it can pass real version
// info without forking a copy of the settings struct.
func DefaultSettings(buildInfo component.BuildInfo) otelcol.CollectorSettings {
	if buildInfo.Command == "" {
		buildInfo = DefaultBuildInfo
	}
	return otelcol.CollectorSettings{
		BuildInfo: buildInfo,
		Factories: components,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					envprovider.NewFactory(),
					fileprovider.NewFactory(),
					httpprovider.NewFactory(),
					httpsprovider.NewFactory(),
					yamlprovider.NewFactory(),
				},
			},
		},
	}
}

// HasReceiver reports whether a receiver factory with the given type
// (e.g. "obi", "hostmetrics") is registered in this binary. Doctor
// (M11, ADR-0020) calls this to differentiate "operator enabled OBI
// but the binary was built without it" from "OBI is wired in and the
// only thing left to check is the host's eBPF readiness". Returns
// false when the factory map fails to build, which would itself be a
// much bigger problem caught by `conduit run` directly.
//
// We rebuild the factories map on every call rather than caching;
// the cost is negligible (each factory's New is a tiny constructor)
// and skipping the cache means there's nothing to invalidate when
// future builds inject components dynamically (e.g. via plugins).
func HasReceiver(typeName string) bool {
	factories, err := components()
	if err != nil {
		return false
	}
	for typ := range factories.Receivers {
		if typ.String() == typeName {
			return true
		}
	}
	return false
}

// Run starts the embedded OTel Collector with the given settings and blocks
// until ctx is canceled or the collector exits with an error. Callers must
// have populated settings.ConfigProviderSettings.ResolverSettings.URIs (e.g.
// with a "yaml:..." entry produced by internal/expander) before calling;
// otherwise the collector reports a "no config sources" error.
func Run(ctx context.Context, settings otelcol.CollectorSettings) error {
	if len(settings.ConfigProviderSettings.ResolverSettings.URIs) == 0 {
		return fmt.Errorf("collector.Run: settings.ConfigProviderSettings.ResolverSettings.URIs is empty; nothing to load")
	}
	col, err := otelcol.NewCollector(settings)
	if err != nil {
		return fmt.Errorf("collector.Run: build collector: %w", err)
	}
	return col.Run(ctx)
}
